server:
  port: 1112

spring:
  banner:
    location: classpath:static/banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/give_bot_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

telegram:
  bot:
    username: '@smart_give_Bot'
    token: '6024442983:AAHBUpMhMalZ8QhpbYcBq7x8nDyjSdcqF8Y'
  group:
    chatId: '-1001912168610'